import Head from 'next/head'
import Hero from "../components/Hero";
import About from '../components/About';
import ProjectGird from "../components/ProjectGrid";

export default function Home() {
  return (
    <div className='bg-[#1F2937] '>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero />
      <About />
      <ProjectGird />

    </div>
  )
}
